Enable eslint rule and reject with errors instead of strings
anza-xyz/solana-web3.js pull request #42
Opened 2024-12-15 22:52 UTC by kox

Following #13 , this PR intends to enable the eslint rule: `prefer-promise-reject-errors` as error.

I believe that treating promise rejections as errors ensures better handling and propagation of the rejection reason to the final components. The affected package tests have been updated accordingly.

2025-01-02 18:43 UTC, steveluscher requested changes
The `reason` property of an `AbortSignal` can actually be an `Error`.

Consider the difference between:

```ts
const ac = new AbortController();
ac.signal.addEventListener('abort', function () { console.log(this.reason.constructor, this.reason); })
ac.abort();
```

…and…

```ts
const ac = new AbortController();
ac.signal.addEventListener('abort', function () { console.log(this.reason.constructor, this.reason); })
ac.abort('o no');
```

`reason` is a `DOMException` in the first, and a `String` in the second.

I think there are only two ways forward here:

* Leave this as is, suppress the lint.
* If the `reason` is `typeof string` then wrap it in an `Error`. Otherwise, reject with `reason` directly.

I think the second raises more questions than it answers, so I'm inclined to do the first.

2025-01-04 21:38 UTC, kox commented
Following your concerns and for simplicity, I suppressed the lints and introduced Errors inside of a test and an example.

2025-01-20 06:00 UTC, steveluscher requested changes
I still think the `Error` conversions need to go.

2025-01-20 06:00 UTC, steveluscher commented on examples/rpc-transport-throttled/src/example.ts
> +                    reject(new Error(this.reason));
Again, if the call to `AbortController#abort` had no `reason` argument, the `reason` would materialize as a `DOMException`. The code that you wrote here would be the equivalent of:

```ts
reject(
    new Error(
        (new DOMException(...)).toString(),
    ),
);
```

…when what you want to do is to throw the `DOMException` as is.

2025-01-20 06:00 UTC, steveluscher commented on packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
> +                            reject(new Error((e.target as AbortSignal).reason));
I think the aim of the tests is to demonstrate that the `reason` gets thrown as-is. All this conversion does is to get in the way of that.

2025-01-20 13:37 UTC, kox commented
Sorry about that. I took a deeper look into the AbortController and AbortSignal and you are right about it. It doesn't make sense to wrap it in an extra Error.

2025-01-20 20:08 UTC, steveluscher approved these changes
Thanks for improving our code quality!

2025-01-21 18:33 UTC, merged